<!-- ======================================================================
 http://jdash.sourceforge.net
  $Id:$
     ====================================================================== -->
<skin name="JDash / Common Resources">

  <description>Common Default Skin Resources</description>


  <!-- Sound resources -->
  <resource type="sound" name="alarm-01"						value="alarm-01.mp3"/>  

  <!-- Image resources -->
  <resource type="image" name="rpm-01"                      value="rpm-01.jpg"/> 
  <resource type="image" name="af-01"                       value="af-01.jpg"/>
  <resource type="image" name="red-toggle-off"              value="red-toggle-switch-off.gif"/> 
  <resource type="image" name="red-toggle-on"               value="red-toggle-switch-on.gif"/> 
  <resource type="image" name="red-push-off"                value="red-push-switch-off.jpg"/> 
  <resource type="image" name="red-push-on"                 value="red-push-switch-on.jpg"/> 
  <resource type="image" name="red-indicator-light-on"		value="red-indicator-light-on.jpg"/>
  <resource type="image" name="red-indicator-light-off"		value="red-indicator-light-off.jpg"/>
  
  
  <!-- Color definitions -->
  <resource type="color" name="black"        value="#000000" />
  <resource type="color" name="white"        value="#ffffff" />
  <resource type="color" name="lite-gray"    value="#0c0c0c" />
  <resource type="color" name="red"          value="#ff0000" />
  <resource type="color" name="dark-red"     value="#990000" />
  <resource type="color" name="orange"       value="#F87431" />
  <resource type="color" name="dark-orange"  value="#C35617" />
  <resource type="color" name="green"        value="#00ff00" />
  <resource type="color" name="dark-green"   value="#306754" />
  <resource type="color" name="dark-blue"    value="#0000ff" />
  <resource type="color" name="blue"         value="#2554C7" />
  <resource type="color" name="yellow"       value="#fffb0b" />
  
  <!-- Font resources -->
  <resource type="font" name="digital" value="digital.ttf" />
  <resource type="font" name="Arial" value="system:Arial"/>


  
</skin>