
	/**Do NOT Modify. Generated by ant build task */
	package net.sourceforge.JDash;
	public interface Version
	{
		public static final int MAJOR = 0;
		public static final int MINOR = 9;
		public static final int BUILD = 19;
		public static final String BUILD_DATE = "01-14-2008";
	}
		